#!python

import argparse
import os
from subprocess import call, check_call

from sitetools.repos import iter_available_packages
from sitetools.sites import Site, find_dev_sites


parser = argparse.ArgumentParser()
parser.add_argument('--list', action='store_true', help='list all availible tools')
parser.add_argument('--all', action='store_true', help='install all availible tools')
parser.add_argument('--rebuild', action='store_true', help='rebuild all installed tools')
parser.add_argument('name', nargs='*')
args = parser.parse_args()


def get_dev_site(create=True):

    dev_sites = find_dev_sites()
    dev_venvs = [s for s in dev_sites if s.is_venv]

    if len(dev_venvs) > 1:
        print 'Multiple development virtualenvs found:'
        for i, site in enumerate(dev_venvs):
            print '%d) %s' % (i + 1, site.prefix)
        index = int(raw_input('Which to use? [1]: ').strip() or '1')
        return dev_sites[dev_venvs[index - 1]]

    elif not dev_venvs:
        if create:

            # The `dev` command will interactively create venvs for us.
            ret = call(['dev', 'true'])
            if ret:
                exit(ret)

            # Try again, but don't call dev again.
            return get_dev_site(create=False)

        else:
            print 'Could not find development virtualenv.'
            exit(1)

    else:
        return dev_venvs[0]


tools = list(iter_available_packages())
name_to_tool = dict((tool['name'], tool) for tool in tools)

if args.list:
    for tool in tools:
        print '{name:22s} {repo}'.format(**tool)
    exit(0)


dev_site = get_dev_site()
tool_dir = os.path.dirname(os.path.abspath(dev_site.prefix))
pip = dev_site.which('pip')

names = [tool['name'] for tool in tools] if args.all or args.rebuild else args.name
if args.rebuild:
    names = [name for name in names if os.path.exists(os.path.join(tool_dir, name))]

for name in names:

    repo = name_to_tool.get(name, {}).get('repo')
    if not repo:
        print 'Tool %r is unknown.' % name
        exit(1)

    tool_path = os.path.join(tool_dir, name)

    if not os.path.exists(tool_path):
        check_call(['git', 'clone', repo, name], cwd=tool_dir)

    if os.path.exists(os.path.join(tool_path, 'Makefile')):
        check_call(['make'], cwd=tool_path)
    
    if os.path.exists(os.path.join(tool_path, 'setup.py')):
        check_call([pip, 'install', '-e', tool_path])

